#!/bin/sh

PROJECT_ROOT=$(git rev-parse --show-toplevel)
pushd $PROJECT_ROOT > /dev/null

export DB_URI="datomic:free://localhost:4334/character-sheet";
export HTTP_SERVER_PORT=4000
java -jar ./target/build/app.jar server

popd > /dev/null 